RBAC- and proxy servlets
StyraInc/styra-run-sdk-java pull request #6
Opened 2022-11-15 17:24 UTC by johanfylling

Implements STY-14741

2022-11-18 23:53 UTC, wusticality commented
Particularly since these repositories are public-facing, I think we should write detailed descriptions for new PRs, I think a high-level overview of what the PR does would be helpful, not just for others but for me haha

2022-11-18 23:55 UTC, wusticality commented on core/src/main/java/com/styra/run/ApiClient.java
> +import com.styra.run.exceptions.RetryException;
Dead code? Didn't see any other changes in this file

2022-11-18 23:56 UTC, wusticality commented on core/src/main/java/com/styra/run/BlockingApiClient.java
> +import com.styra.run.exceptions.RetryException;
Dead code?

2022-11-19 00:04 UTC, wusticality commented on sdk/src/main/java/com/styra/run/DefaultApiClient.java
> +import com.styra.run.exceptions.RetryException;
Dead code?

2022-11-21 10:12 UTC, johanfylling commented on core/src/main/java/com/styra/run/ApiClient.java
> +import com.styra.run.exceptions.RetryException;
No, I've just moved this exception into a different package. Previously, it resided in the same package as this class, which doesn't require an import.

2022-11-21 10:12 UTC, johanfylling commented on core/src/main/java/com/styra/run/BlockingApiClient.java
> +import com.styra.run.exceptions.RetryException;
No; same reason as above.

2022-11-21 10:12 UTC, johanfylling commented on sdk/src/main/java/com/styra/run/DefaultApiClient.java
> +import com.styra.run.exceptions.RetryException;
No.

2022-11-21 16:57 UTC, wusticality commented on core/src/main/java/com/styra/run/session/TenantInputTransformer.java
> +            inputValue.entrySet().stream()
In the `golang` SDK I only inject the `tenant` and `session` keys if _both_ keys are unset

2022-11-21 16:58 UTC, wusticality commented on core/src/main/java/com/styra/run/session/TenantSession.java
> +        super(require(map, (m) -> m.containsKey(TENANT_KEY),
Shouldn't we require both keys here?

2022-11-21 17:03 UTC, wusticality commented on servlet/src/main/java/com/styra/run/session/CookieSessionManager.java
> +                        String[] components = cookie.getValue().split("\\s*/\\s*", 2);
Should probably only look for the cookie named `"user"` here, no?

2022-11-21 17:18 UTC, wusticality commented on core/src/main/java/com/styra/run/Proxy.java
> +public class Proxy<S extends Session> {
I'm not sure how `java` modules work but you may want to rename this file like `BatchQueryProxy` as you'll need to add proxies for the CRUD operations and also `Query` / `Check`. I'd probably put them in a subfolder at minimum

2022-11-21 17:20 UTC, wusticality commented on core/src/main/java/com/styra/run/rbac/RbacManager.java
>      private final StyraRun styraRun;
To be consistent with the `golang` SDK, I wonder if we shouldn't rename this type to `client` or something similar

2022-11-21 17:22 UTC, wusticality commented on core/src/main/java/com/styra/run/rbac/RbacManager.java
> +    public CompletableFuture<Void> setUserBinding(UserBinding userBinding, TenantSession session) {
To be consistent with the `golang` SDK and our docs, I'd recommend calling this `putUserBinding`

2022-11-21 17:23 UTC, wusticality commented on core/src/main/java/com/styra/run/rbac/RbacManager.java
> +    public CompletableFuture<List<UserBinding>> listUserBindings(TenantSession session) {
I'd call these `listUserBindingsAll` and `listUserBindings` to be consistent

2022-11-21 17:26 UTC, wusticality commented on core/src/test/groovy/com/styra/run/rbac/RbacManagerSpec.groovy
> +        def authzInput = new TenantSession('alice', 'AcmeCorp')
Should `AcmeCorp` be lowercase?

2022-11-21 17:36 UTC, wusticality commented
It won't let me comment on parts of the `README` for some reason, so dropping a few comments here:

* Seems like it should be possible to boot the client without environment variables, no?
* I'd call the client `Proxy` section `BatchQuery`.
* You may want to reorder the various sections to mirror the `golang` `README`.
* I think you should document the RBAC functions as well. The `golang` `README` also shows example outputs so the user can get a feel for how the request payload / response looks.

2022-11-21 17:37 UTC, wusticality requested changes
Nice work! Some questions / comments / changes

2022-11-22 09:41 UTC, johanfylling commented on core/src/main/java/com/styra/run/session/TenantInputTransformer.java
> +            inputValue.entrySet().stream()
When this tenant/subject strategy is in effect, I think it's a mistake to let the client-side dictate relevant session info under _any_ circumstances. An attacker could simply opt to not send the session cookie, and just inject whatever session info they want to spoof into all the query inputs.

2022-11-22 09:49 UTC, johanfylling commented on servlet/src/main/java/com/styra/run/session/CookieSessionManager.java
> +                        String[] components = cookie.getValue().split("\\s*/\\s*", 2);
That's done above, on line 22. The cookie name is configurable.

2022-11-22 09:50 UTC, johanfylling commented on core/src/main/java/com/styra/run/Proxy.java
> +public class Proxy<S extends Session> {
Yea. I'm making some of those changes in my task to integrate the testing-framework. I'll include these modifications in that PR.

2022-11-22 09:53 UTC, johanfylling commented on core/src/main/java/com/styra/run/rbac/RbacManager.java
>      private final StyraRun styraRun;
I feel `client` is a bit too generic. In Node, we also call it `StyraRun`. Perhaps `StyraRunClient` is a good middle-ground.
The way Java deals with imports, makes too generic names that may overlap with other libraries a huge pain.

2022-11-22 09:57 UTC, johanfylling commented on core/src/main/java/com/styra/run/rbac/RbacManager.java
> +    public CompletableFuture<Void> setUserBinding(UserBinding userBinding, TenantSession session) {
Sure, I'll make that change.

What are "our docs", btw? We have that google-doc with the SDK overview. We discussed transcribing that into markdown and putting it into the test-framework repo; but I haven't seen that.

2022-11-22 10:17 UTC, johanfylling commented on core/src/main/java/com/styra/run/rbac/RbacManager.java
> +    public CompletableFuture<List<UserBinding>> listUserBindings(TenantSession session) {
Java lends itself to function-overloading, but I can rename this to `listAllUserBindings`, to be consistent (doesn't that have a better flow to it?).

I'm thinking:

* `listAllUserBindings()`: for fetching all bindings known to Styra Run. To be avoided in systems with many bindings. This probably needs to be changed to eventually return a cursor of some sort, that pumps pages as-defined by Styra Run.
* `listUserBindings()`: for fetching paginated bindings known to Styra Run. User can define pagination and search parameters; both of which needs support in Styra Run.
* `getUserBinsings()`:  takes a list of users, for which we'll fetch bindings.

I don't recall exactly how our previous discussion regarding this went, to be honest 😅 .

2022-11-22 11:16 UTC, johanfylling commented
I intentionally didn't put too much effort into the README, as I think we should go through all of the SDK READMEs to define an appropriate template to follow everywhere.

2022-11-22 18:12 UTC, wusticality commented on core/src/main/java/com/styra/run/session/TenantInputTransformer.java
> +            inputValue.entrySet().stream()
Ah, I see. I'll fix that in the `golang` SDK as well

2022-11-22 18:26 UTC, wusticality approved these changes
lgtm

2022-11-23 08:20 UTC, merged